@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault

package com.hexagram2021.randomcrafting;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;